version: 2

jobs:
  build:
    macos:
      xcode: "10.1.0"

    steps:

      - checkout

      - restore_cache:
          name: Restore Pods cache
          keys:
            - v2-pods-{{ checksum "Podfile.lock" }}

      - run:
          name: Install Pods
          command: ./scripts/ci_pod_install

      - save_cache:
          name: Saving Pods cache
          key: v2-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
            - ~/.cocoapods

      - run:
          name: Install additional tools
          command: |
            gem install xcpretty --user-install

      - run:
          name: Tests on iOS 12
          command: ./scripts/ci_test 'platform=iOS Simulator,name=iPhone 7,OS=12.1' logs_xcbuild_ios_12.txt
      - store_artifacts:
          path: logs_xcbuild_ios_12.txt
          destination: logs_xcbuild_ios_12.txt

      - run:
          name: Tests on iOS 11
          command: ./scripts/ci_test 'platform=iOS Simulator,name=iPhone 7,OS=11.2' logs_xcbuild_ios_11.txt
      - store_artifacts:
          path: logs_xcbuild_ios_11.txt
          destination: logs_xcbuild_ios_11.txt

      - run:
          name: Tests on iOS 10
          command: ./scripts/ci_test 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' logs_xcbuild_ios_10.txt
      - store_artifacts:
          path: logs_xcbuild_ios_10.txt
          destination: logs_xcbuild_ios_10.txt
